package mysql

// Framework code is generated by the generator.

import (
	"fmt"
	"github.com/bytebase/bytebase/backend/plugin/advisor"
	"github.com/bytebase/bytebase/backend/plugin/advisor/catalog"
	"github.com/bytebase/bytebase/backend/plugin/advisor/db"
	"github.com/pingcap/tidb/parser/ast"
)

var (
	_ advisor.Advisor = (*ColumnDisallowDropInIndexAdvisor)(nil)
	_ ast.Visitor     = (*columnDisallowDropInIndexChecker)(nil)
)

func init() {
	advisor.Register(db.MySQL, advisor.MySQLColumnDisallowDropInIndexKeys, &ColumnDisallowDropInIndexAdvisor{})
	advisor.Register(db.TiDB, advisor.MySQLColumnDisallowDropInIndexKeys, &ColumnDisallowDropInIndexAdvisor{})
}

// ColumnDisallowDropInIndexAdvisor is the advisor checking for disallow drop column in index keys
type ColumnDisallowDropInIndexAdvisor struct {
}

// Check checks for disallow drop column in index keys
func (*ColumnDisallowDropInIndexAdvisor) Check(ctx advisor.Context, statement string) ([]advisor.Advice, error) {
	stmtList, errAdvice := parseStatement(statement, ctx.Charset, ctx.Collation)
	if errAdvice != nil {
		return errAdvice, nil
	}

	level, err := advisor.NewStatusBySQLReviewRuleLevel(ctx.Rule.Level)
	if err != nil {
		return nil, err
	}
	checker := &columnDisallowDropInIndexChecker{
		level: level,
		title: string(ctx.Rule.Type),
	}

	for _, stmt := range stmtList {
		checker.text = stmt.Text()
		checker.line = stmt.OriginTextPosition()
		(stmt).Accept(checker)
	}

	if len(checker.adviceList) == 0 {
		checker.adviceList = append(checker.adviceList, advisor.Advice{
			Status:  advisor.Success,
			Code:    advisor.Ok,
			Title:   "OK",
			Content: "",
		})
	}
	return checker.adviceList, nil
}

type columnDisallowDropInIndexChecker struct {
	adviceList []advisor.Advice
	level      advisor.Status
	title      string
	text       string
	line       int
	catalog    *catalog.Finder
}

// Enter implements the ast.Visitor interface.
func (checker *columnDisallowDropInIndexChecker) Enter(in ast.Node) (ast.Node, bool) {
	if node, ok := in.(*ast.AlterTableStmt); ok {
		for _, spec := range node.Specs {
			if spec.Tp != ast.AlterTableDropColumn {
				continue
			}

			tableName := node.Table.Name.O
			column := spec.OldColumnName.Name.O

			for _, index := range node.Table.TableInfo.Indices {
				for _, indexColumn := range index.Columns {
					if column == indexColumn.Name.O {
						checker.adviceList = append(checker.adviceList, advisor.Advice{
							Status: checker.level,
							Code:   advisor.DropColumnInIndex,
							Title:  checker.title,
							Content: fmt.Sprintf("Drop column `%s`.`%s` in index `%s`",
								tableName, column, index.Name.O),
							Line: node.OriginTextPosition(),
						})
					}
				}
			}
		}
	}

	return in, false
}

// Leave implements the ast.Visitor interface.
func (*columnDisallowDropInIndexChecker) Leave(in ast.Node) (ast.Node, bool) {
	return in, true
}
